plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'ext/ssr_deno/target/**/*'
    - 'plans/**/*'
    - 'samples/**/*'
    - 'scripts/**/*'
    - 'tmp/**/*'
    - 'test/dummy/**/*'
    - 'test/internal/**/*'
    - 'vendor/**/*'

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Exclude:
    - 'scripts/**/*'
    - 'test/**/*'
    - 'rakelib/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'rakelib/**/*'
    - 'scripts/**/*'
    - 'ssr-deno.gemspec'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'scripts/**/*'
    - 'test/**/*'
    - 'rakelib/**/*'

Metrics/MethodLength:
  Max: 15
  CountAsOne:
    - array
    - hash
    - heredoc
  Exclude:
    - 'scripts/**/*'
    - 'test/**/*'
    - 'rakelib/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'scripts/**/*'
    - 'test/**/*'
    - 'rakelib/**/*'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

ThreadSafety/NewThread:
  Exclude:
    - 'scripts/**/*'
    - 'test/**/*'
Naming/VariableNumber:
  EnforcedStyle: snake_case
  Exclude:
    - 'scripts/**/*'

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
