plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15
  CountAsOne:
    - array
    - hash
    - heredoc

Naming/RescuedExceptionsVariableName:
  PreferredName: error
Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
