module SSR
  module Deno
    VERSION: String

    class Error < StandardError
    end

    class JsRuntimeInitializationError < Error
    end

    class JsRuntimeNotInitializedError < Error
    end

    class JsRuntimeWorkerError < Error
    end

    class RenderError < Error
    end

    class << self
      def init_runtime: (String bundle_path) -> bool?
      def render: (Hash[untyped, untyped] data) -> String
      def native_render: (String json) -> String
      def native_version: () -> String
    end
  end
end
