name: CI

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

env:
  V8_FROM_SOURCE: 'true'
  GN_ARGS: 'v8_monolithic=true v8_monolithic_for_shared_library=true'
  RB_SYS_CARGO_PROFILE: 'dev'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: CI - ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3'
          - '3.4'
          - '4.0'

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Compile native extension
        run: bundle exec rake compile
      - name: Build Vite SSR sample bundle
        run: bundle exec rake samples:build
      - name: Run tests
        run: bundle exec rake test
      - name: Run RuboCop
        run: bundle exec rubocop
      - name: Validate RBS signatures
        run: bundle exec rake rbs
